# Numpy
## Introduccion
Numpy oferece una gran variedad de herramientas para realizar calculos numericos, con metodos muy cercanos al harwdware de nuestra computadora, por lo cual, se convierte en una herrmaienta eficiente en comparacion con otro tipo de contenedores de python (listas o tuplas).

Para importar esta libreria, simplemente:

In [1]:
import numpy as np

El objeto mas basico de numpy es el array, este es el equivalente a una lista de python, se puede declarar a partir de cualquier tipo de listas. Podemos representar vectores, matrices o incluso tensores con este objeto:

In [5]:
vector = np.array([1,2,3])
matrix = np.array([[1,2],[3,4]])
tensor = np.array([[[1,2],[3,4]],
                                    [[5,6],[7,8]]])
print('vector:\n', vector)
print('matrix:\n', matrix)
print('tensor:\n', tensor)

vector:
 [1 2 3]
matrix:
 [[1 2]
 [3 4]]
tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Estos objetos poseen una serie de parametros que suelen ser de mucha utilidad:
*   *ndim*: devuelve la dimension del array
*   *size*: duvuelve el numero de elementos en un array
*   *shape*: devuelve las dimensiones de un array como una tupla (filas, columnas)




In [7]:
print(vector.ndim, matrix.ndim, tensor.ndim)
print(vector.size, matrix.size, tensor.size)
print(vector.shape, matrix.shape, tensor.shape)

1 2 3
3 4 8
(3,) (2, 2) (2, 2, 2)


note que el vector es considerado como un vector columna en automatico

Existe una clase que es el equivalente al rango en python, su sintaxis es la siguiente:

`np.arange(start, stop, step, dtype=None)`

In [8]:
arr1 = np.arange(0, 100, 5)
arr1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

Por otro lado, si necesitamos crear un array especificando un inicio, un final y un numero exacto de divisiones, podemos usar *linspace*, cuya sintaxis es la siguiente:

```
np.linspace(start, stop, divitions)
```



In [9]:
arr2 = np.linspace(0,10,11)
arr2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Tambien podemos crear matrices de dimension especifica llena unicamente de 0s y 1s, con los objetos *ones* y *zeros*, su sintaxis es como sigue:

```
np.zeros((rows, columns))
np.ones((rows, columns))
```



In [10]:
m1 = np.zeros((2,3))
m2 = np.ones((4,3))
print(m1,'\n',m2)

[[0. 0. 0.]
 [0. 0. 0.]] 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Tambien podemos crear matrices cuadradas (n x n) diagonales, por ejemplo la matriz identidad con la clase eye, el cual solo se le debe especificar la dimension de la matriz:


```
np.eye(dimention)
```
o la clase diag, la cual recibe una lista de numeros que apreceran en la diagonal principal:


```
np.diag([n1,n2,...])
```

In [11]:
m3 = np.eye(3)
m4 = np.diag([1,2,3])
print(m3,'\n',m4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


 Tambien podemos trabajar con numeros aleatorios, para ello incluso podemos declarar una semillar como:

```
np.random.seed(semilla)
```
Posteriormente, podemos generar numeros aleatorios entre cierto rango [lim_in, lim_sup] como:

```
np.random.randint(lim_inf, lim_sup)
```

In [14]:
np.random.seed(1)
num = np.random.randint(1,10)
num

6

Tambien podemos generar arrays con numeros aleatorios de manera lineal (entre 0 y 1) con *random.rand* o normal con *random.randn*:

```
np.random.rand(no. de elementos)
np.random.randn(no. de elementos)
```

In [16]:
arr1 = np.random.rand(10)
arr2 = np.random.randn(10)
print(arr1)
print(arr2)

[0.09280081 0.51815255 0.86502025 0.82914691 0.82960336 0.27304997
 0.0592432  0.67052804 0.59306552 0.6716541 ]
[-1.30486124 -0.38057504 -0.74362701 -0.43712177 -0.42645009  1.3814073
  0.09837051 -0.36945748 -1.27321995  1.0149868 ]


Tambien podemos generar arrays con numeros aleatorios entre cierto intervalo y con un tamano especifico, la sintaxis es como sigue:

```
np.random.randint(lim_inf, lim_sup, size=(#filas, #columnas))
```

In [18]:
matrix = np.random.randint(1,10,size=(2,3))
matrix

array([[3, 8, 8],
       [9, 7, 4]])

Tambien pdemos hacer estos con las distribuciones lineales y normales, especificando la dimension de la matriz deseado, la sintaxis es la siguiente:

```
np.random.random((#filas, $columnas))
np.random.randomn((#filas, $columnas))
```

In [19]:
m1 = np.random.random((3,4))
m1

array([[0.29361415, 0.28777534, 0.13002857, 0.01936696],
       [0.67883553, 0.21162812, 0.26554666, 0.49157316],
       [0.05336255, 0.57411761, 0.14672857, 0.58930554]])

Note que todas las clases usadas para generar matrices devuelven un objeto de tipo array, por esta razon, podemos seguir haciendo uso de estas herramientas y sus parametros sin ningun problema.

## Tipos de datos
Algunas de las clases usadas en la seccion anterior devuelven matrices con elementos de tipo entero o flotante, en ocaciones necesitaremos realizar trnasformaciones de los datos obtenidos. Por ejemple, en el caso de una matriz con datos flotantes:

In [20]:
mfloat = np.ones((2,3))
mfloat

array([[1., 1., 1.],
       [1., 1., 1.]])

Podemos realizar tranformaciones a enteros o strings  con el metodo *astype*, la sintaxis es como sigue:

```
np.array.astype(int/float/string/bool/etc)
```

In [21]:
mint = mfloat.astype(int)
mstr = mfloat.astype(str)
mbool = mfloat.astype(bool)
print(mint)
print(mstr)
print(mbool)

[[1 1 1]
 [1 1 1]]
[['1.0' '1.0' '1.0']
 ['1.0' '1.0' '1.0']]
[[ True  True  True]
 [ True  True  True]]


## Indexasion
En cuanto a la indexasion, esta se realiza de manera similar a las listas y tuplas de python, donde si *a* es un *array*, *a* se indexa desde el elemento 0 hasta el n-1, y *a[i]* devuelve el i-esimo elemento.

In [23]:
a = np.arange(1,11)
print(a)
print(a[2])

[ 1  2  3  4  5  6  7  8  9 10]
3


Podemos indexar elementos especificos con listas:

In [26]:
a[[1,3]]

array([2, 4])

note que el objeto devuelto es de clase array, lo cual permite obtener elementos en especifico manteniendo el formato de la clase.

En el caso de arrays multidimensionales, el indexado se realiza de una manera muy practica, si *a* es un array multidimensional, se indexa con *n* indices, donde *n* es la dimension del array:

```
a[d1,d2,...dn]
```

In [29]:
m = np.eye(5)
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
m[2,2]

1.0

El slicing funciona de manera similar a cuando se trabaja con listas de python, sin embargo, podemos eralizar slicing en filas y columnas de manera simultanea. Por ejemplo, en el caso de un vector, podemos realizarlo de la manera tradicional

In [31]:
vec = np.arange(0,11)
vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
vec[4:9]

array([4, 5, 6, 7, 8])

de la misma manera, podemos realizar slicing con matrices para obtener ciertas porciones de la misma:

In [35]:
matrix = np.random.randint(1,10,size=(4,4))
matrix

array([[4, 1, 9, 7],
       [5, 6, 7, 3],
       [6, 8, 9, 5],
       [5, 8, 8, 5]])

In [36]:
matrix[2:,2:]

array([[9, 5],
       [8, 5]])

incluso podemos modificar el contenido de estas matrices con slices:

In [37]:
matrix[-1,0:] = 0
matrix

array([[4, 1, 9, 7],
       [5, 6, 7, 3],
       [6, 8, 9, 5],
       [0, 0, 0, 0]])

tambien podemos relizar slicing con operaciones, porejemplo:

In [44]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
b = a[a%2 == 0]
b

array([ 2,  4,  6,  8, 10])

Debemos tener cuidado al declarar arrays como en el ejemplo anterior, ya que de esta manera *a* y *b* comparten la misma direccion de memoria, por lo tanto, modificar *b* modificadra *a* y viceversa:

In [47]:
v1 = np.arange(1,10)
v2 = v1[4:8]
np.shares_memory(v1,v2)

True

Para resolver este inconveniente podemos hacer uso del metodo *copy()* para garantizar que *v2* se asigne en una direccion de memoria diferente:

In [48]:
v1 = np.arange(1,10)
v2 = v1[4:8].copy()
np.shares_memory(v1,v2)

False

## Operaciones comunes
Podemos realizar operaciones con  *escalares*, en el sentido en el que operan componente a componente con cada elemento del array, podemos realizar: suma, resta, multiplicacion, division, y elevar a exponentes:

In [50]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
a-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [55]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Tambien podemos realizar operaciones entre un par de arrays operando componente a componente de cada uno:

In [57]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
b = np.arange(11,21)
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
a+b

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [60]:
b-a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [61]:
a*b

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [62]:
a/b

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

Para realizar verdaderas operaciones matriciales se hace uso del *producto punto*, el cual simplemente realiza una multiplicacion de matrices (con la definicion formal)

In [63]:
m1 = np.random.randint(1, 10, size=(4,2))
m1

array([[1, 3],
       [1, 8],
       [2, 8],
       [9, 5]])

In [65]:
m2 = np.random.randint(1, 10, size=(2,3))
m2

array([[3, 7, 1],
       [3, 7, 7]])

In [66]:
m1.dot(m2)

array([[12, 28, 22],
       [27, 63, 57],
       [30, 70, 58],
       [42, 98, 44]])

Tambien podemos realizar transposiciones de matrices con dos metodos distintos:

In [67]:
m1.T

array([[1, 1, 2, 9],
       [3, 8, 8, 5]])

In [68]:
np.transpose(m1)

array([[1, 1, 2, 9],
       [3, 8, 8, 5]])

Por ejemplo si queremos hacer un producto punto entre dos vectores:

In [69]:
a = np.arange(1,11)
b = np.arange(11,21)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [70]:
aT = a.T
aT.dot(b)

935

Tambien podemos realizar comparaciones con arrays:

In [71]:
a = np.arange(1,11)
b = np.arange(11,21)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [72]:
a<b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [73]:
a==b

array([False, False, False, False, False, False, False, False, False,
       False])

Tambien podemos calcular varias operaciones con el caontenido de cada array, por ejemplo para un vector:

In [75]:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [77]:
np.max(a)

4

In [78]:
np.min(a)

0

In [79]:
np.sum(a)

10

In [81]:
np.mean(a)

2.0

In [82]:
np.median(a)

2.0

In [83]:
np.var(a)

2.0

In [84]:
np.std(a)

1.4142135623730951

Por otro lado, tambien podemos realizar estas operaciones con matrices, para ello debe quedar claro que estas operaciones se realizan por ejes, donde el eje 0 corresponde al vertical (columnas) y el eje 1 al horizontal (filas). Por ejmplo:

In [85]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
np.sum(m, axis=0) # columnas

array([12, 15, 18])

In [87]:
np.sum(m, axis=1) # filas

array([ 6, 15, 24])

## Ordenamiento
Numpy implementa un metodo para ordenar de manera ascendente los elementos de un array, el metodo es *sort()*, por ejemplo, para un vector:

In [89]:
vec = np.array([4,5,1,3,2])
vec

array([4, 5, 1, 3, 2])

In [90]:
np.sort(vec)

array([1, 2, 3, 4, 5])

Tambien se puede usar con matrices:

In [92]:
m = np.random.randint(1,10, size=(3,3))
m

array([[7, 6, 2],
       [3, 2, 6],
       [5, 1, 8]])

In [93]:
np.sort(m)

array([[2, 6, 7],
       [2, 3, 6],
       [1, 5, 8]])

In [95]:
np.sort(m, axis=0)

array([[3, 1, 2],
       [5, 2, 6],
       [7, 6, 8]])

## Redimensionar arrays
Numpy ofrece una gran variedad de metodos para redimensionar cualquier arrays, por ejemplo, *ravel()* extiende cualquier matriz en un vector unidimensional:

In [97]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
m.ravel()

array([1, 2, 3, 4, 5, 6])

Tambien podemos hacer uso del metodo *reshape* para redimensionar cualquier matriz de la forma (#filas, #columnas), siempre y cuando la dimension actual permita acomodar los objetos de esta manera:

In [100]:
m = np.random.randint(1,5, size=(6,6))
m

array([[2, 1, 2, 2, 4, 1],
       [2, 4, 2, 2, 3, 2],
       [1, 1, 4, 3, 2, 1],
       [4, 4, 1, 4, 2, 3],
       [4, 2, 2, 1, 2, 1],
       [2, 1, 2, 4, 2, 2]])

In [101]:
m.reshape(1,36)

array([[2, 1, 2, 2, 4, 1, 2, 4, 2, 2, 3, 2, 1, 1, 4, 3, 2, 1, 4, 4, 1, 4,
        2, 3, 4, 2, 2, 1, 2, 1, 2, 1, 2, 4, 2, 2]])

In [102]:
m.reshape(2,18)

array([[2, 1, 2, 2, 4, 1, 2, 4, 2, 2, 3, 2, 1, 1, 4, 3, 2, 1],
       [4, 4, 1, 4, 2, 3, 4, 2, 2, 1, 2, 1, 2, 1, 2, 4, 2, 2]])

In [103]:
m.reshape(3,12)

array([[2, 1, 2, 2, 4, 1, 2, 4, 2, 2, 3, 2],
       [1, 1, 4, 3, 2, 1, 4, 4, 1, 4, 2, 3],
       [4, 2, 2, 1, 2, 1, 2, 1, 2, 4, 2, 2]])

In [104]:
m.reshape(4,9)

array([[2, 1, 2, 2, 4, 1, 2, 4, 2],
       [2, 3, 2, 1, 1, 4, 3, 2, 1],
       [4, 4, 1, 4, 2, 3, 4, 2, 2],
       [1, 2, 1, 2, 1, 2, 4, 2, 2]])

Si un *reshape()* no esta permitido por la dimension actual del array, entonces podemos recurrir al metodo *resize()*, el cual funciona de la misma maner aque *reshape()* pero permite cualquier dimension agregando 0s para los espacios faltantes:

In [107]:
a = np.array([0,1,2,3,4])
a.resize((10,))
a

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])